version: '3.3'

services:
  web:
    image: nginx:${NGINX_VERSION}
    container_name: ${NGINX_NAME}
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ${APP_DIR}:/var/www/html
      - ${NGINX_CONF}:/etc/nginx/conf.d/default.conf
  php:
    build:
      context: ${DOCKER_ETC}
      dockerfile: ${DOCKER_PHP}
    image: php-teste
    container_name: php
    volumes:
      - ${APP_DIR}:/var/www/html
  db:
    image: mysql:${MYSQL_VERSION}
    container_name: ${MYSQL_NAME}
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
    volumes:
      - ${MYSQL_DATA}:/var/lib/mysql
  console:
    build:
      context: ${DOCKER_ETC}
      dockerfile: ${DOCKER_CONSOLE}
      args:
        APP_USER: ${APP_USER}
    image: console-teste
    container_name: console
    volumes:
      - ${APP_DIR}:/code
    user: ${APP_USER}
    stdin_open: true
    tty: true
